// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using projeDeneme.Models;

namespace projeDeneme.Migrations
{
    [DbContext(typeof(ModelmysqlContext))]
    partial class ModelmysqlContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854");

            modelBuilder.Entity("projeDeneme.Models.Modelmysql", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Ad");

                    b.Property<string>("Email");

                    b.Property<string>("Soyad");

                    b.Property<string>("deneme");

                    b.HasKey("ID");

                    b.ToTable("Modelmysqls");
                });

            modelBuilder.Entity("projeDeneme.Models.yeniModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Ad");

                    b.Property<string>("Email");

                    b.Property<string>("Soyad");

                    b.Property<string>("deneme");

                    b.HasKey("ID");

                    b.ToTable("YeniModels");
                });
#pragma warning restore 612, 618
        }
    }
}
